bcgov/sbc-qsystem

Jenkinsfile
README.md

Pipeline (#5)

---

Jenkinsfile.prod
Jenkinsfile.test

Source for the promotion strategy

Draft promotion sources

---

QSystem/src/ru/apertum/qsystem/client/forms/FClient.java
QUser/src/java/ru/apertum/qsys/quser/Form.java

Fixed the issues related to activated/deactivated keys on management panel.

Fix Keys on Management panel

---

Documentation/devops/README.md
Openshift/templates/sbc-qsystem-environment-template.json

Documentation and environment template

Service domain

---

QSystem/src/ru/apertum/qsystem/common/CustomerState.java
QSystem/src/ru/apertum/qsystem/common/model/IPriority.java
QSystem/src/ru/apertum/qsystem/common/model/QCustomer.java
QUser/src/java/ru/apertum/qsys/quser/Form.java
QUser/web/include/clientDashboard.zul

- Fix Add next service Bug
- Update Bottom panel table

Bug Fix and Bottom panel update

---

QUser/src/java/ru/apertum/qsys/quser/Form.java

Auto enables "Begin Service" When:
1. Starting Service from Hold
2. Adding Next Service
3. Add and Serve

Fix Begin service Issue

---

QUser/web/WEB-INF/zk.xml

Changed session timeout and max desktop per session

Reloading issue fix

---

QUser/src/java/ru/apertum/qsys/quser/Form.java
QUser/src/java/ru/apertum/qsys/quser/Multilingual.java

- Fix relaod twice issue
- deafult language en_CA

Reload issue Fix

---

QUser/src/java/ru/apertum/qsys/quser/Form.java
QUser/web/include/dialog/addTicketDialog.zul
QUser/web/include/dialog/serveCustomerDialog.zul

- Search Works along with category names
- Show Category names Column while adding tickets

Bug Fix and updates

---

QUser/web/include/dialog/addTicketDialog.zul

- remove right click from the waiting list
- fix null pointer exception in case there's no client in deferred clients

Update and Fix

---

Seeder/sql/V1.0__QSystem_English.sql

Revert "Update Database"

---

QUser/web/include/dialog/serveCustomerDialog.zul

In the Serve Citizen Screen, increase the middle space for fitting 4 services.

modified the UI to fit four services in the middle part.

---

QUser/web/include/clientDashboard.zul
QUser/web/include/dialog/addTicketDialog.zul

Adjust the comment UI based on the reception mode
Update Dashboard to fix scrolling

Adjust UI based on the reception mode

---

QUser/web/include/dialog/addTicketDialog.zul
QUser/web/include/dialog/serveCustomerDialog.zul

Added Channel label and adjust the UI appearance in serveCustomer window and addTicket window

add label for nonrecep, and display channels in serveCustomer wondow

---

QSystem/src/ru/apertum/qsystem/common/cmd/CmdParams.java
QSystem/src/ru/apertum/qsystem/server/controller/Executer.java
QUser/src/java/ru/apertum/qsys/quser/Form.java
QUser/web/include/dialog/addTicketDialog.zul
QUser/web/include/dialog/serveCustomerDialog.zul

Added the functionality that channels is associated with each service. (user could select channels in addNextService btn). 
Remove the default selected service when user add next service, and add function that user has to select service 1st. 
Adjust comment box
Debug list:
1. select Redirect channels in addnextService would only save one service  in DB
2. prompt when try to select channels and service is not selected in addNextService window.

channels associste with service in add next service btn

---

scripts/mount_test.sh

Integrates slack messages on livenessProbe failure.
Requires environment variable $SLACKHOOK.

Mount point

---

functional-tests/src/test/groovy/TicketModule.groovy
functional-tests/src/test/resources/GebConfig.groovy

GAManagementDialogue broke BDD: Geb selector selectservice in TicketModule updated to fix by selecting first visible z-listitem

Geb selector updates after introducing GAManagementDialogue

---

functional-tests/src/test/groovy/AuthModule.groovy
functional-tests/src/test/groovy/FlowSpecs.groovy
functional-tests/src/test/groovy/ServiceModule.groovy
functional-tests/src/test/groovy/TicketModule.groovy

cleaning up the report output.

formatting report

---

QSystem/src/ru/apertum/qsystem/client/forms/FAdmin.java

Ensure we set the smartboard_yn field to "Y" when creating a new service

Ensure we set the smartboard_yn field to "Y" when creating a new service

---

Nginx/conf.d/server.conf.tmpl
QUser/src/java/ru/apertum/qsys/quser/Form.java
QUser/web/include/dialog/addTicketDialog.zul

Added parameter passing to nginx configuration, remove comments from add ticket dialog

Bug fixes and nginx configuration changes

---

QUser/src/java/ru/apertum/qsys/quser/Form.java
QUser/web/include/clientDashboard.zul
QUser/web/index.zul

Revamp how we set the CFMSHidden and CFMSHeight strings, and use zk invalidation to redraw on logout, so it not always shows the correct display.

Fixed the main dashboard showing different viewsets betwen logouts and logins

---

.gitignore

Only adding .settings (Eclipse IDE artifact) to gitignore file

Changing gitignore to ignore Eclipse artifacts

---

Documentation/devops/README.md
Openshift/templates/sbc-qsystem-additional-office.json
Openshift/templates/sbc-qsystem-environment-template.json

Removed the need for QSystem-data persistent volume.

Update Openshift templates after Multitenant modifications to QSystem.

---

functional-tests/src/test/groovy/FlowSpecs.groovy

BDD Tests broke since service names were changed.
Tested to work.

changed service names in BDD to fit new service name schema

---

QSystem/src/ru/apertum/qsystem/common/SoundPlayer.java

Production system causing exceptions trying to play sound.  Commented out this line for now.
NOTE:  Playing chime on smartboard when customer called still works

Comment out playing sound causing exception

---

Openshift/templates/sbc-qsystem-additional-office-clustered.json
Openshift/templates/sbc-qsystem-mysql-clustering.json
QSystem/src/ru/apertum/qsystem/hibernate/AnnotationSessionFactoryBean.java
Seeder/src/main/java/ca/gov/sbc/qsystem/Seeder.java

Added config files for clustering, added environment variable to QSystem to tell system we're clustering, and added suppor to Seeder / qsystem hibernate factory to support the clustered environment

Mysql Clustering

---

QSystem/src/ru/apertum/qsystem/common/cmd/CmdParams.java
QSystem/src/ru/apertum/qsystem/common/model/QCustomer.java
QSystem/src/ru/apertum/qsystem/server/QServer.java
QSystem/src/ru/apertum/qsystem/server/controller/Executer.java
QSystem/src/ru/apertum/qsystem/server/model/QOffice.java
QSystem/src/ru/apertum/qsystem/server/model/QService.java
QSystem/src/ru/apertum/qsystem/server/model/QUser.java
QUser/src/java/ru/apertum/qsys/quser/Form.java
QUser/src/java/ru/apertum/qsys/quser/Form.java.Save
QUser/src/java/ru/apertum/qsys/quser/User.java
QUser/web/include/clientDashboard.zul
QUser/web/include/dialog/ReportingBug.zul
QUser/web/include/dialog/addTicketDialog.zul
QUser/web/include/dialog/serveCustomerDialog.zul
QUser/web/include/loginForm.zul.Save
QUser/web/index.zul
Seeder/sql/V1.7__QSystem_Add_QTxn_fields.sql

Merging changes from upstream master
Fixed the 'Served By' column not persisting across server restarts

Code Cleanup

---

functional-tests/src/test/groovy/AuthModule.groovy

sjrumsby-mbp:functional-tests sjrumsby$ ./gradlew chromeTest
BUILD SUCCESSFUL in 20s
5 actionable tasks: 3 executed, 2 up-to-date

Align gradle selenium tests with new non-dropdown username input field

---

QSystem/src/ru/apertum/qsystem/server/controller/Executer.java

Fix QTxn bug, error when no one waiting, invite clicked

Fix QTxn bug, error when click invite, no one waiting

---

QSystem/src/ru/apertum/qsystem/server/controller/Executer.java
QSystem/src/ru/apertum/qsystem/server/model/QService.java

Change FetchTypes in QService as per Sean, FAdmin now working again
Fix QuickTxn bug found by Sean, didn't check for null cmdParams in Executer, Task class

Fix Q.Txn bug discovered by Sean (didn't check null cmdParams in Task)

---

QSmartboardPlugin/src/ru/apertum/qsystem/smartboard/PrintRecords.java
QSmartboardPlugin/src/ru/apertum/qsystem/smartboard/PrintRecordsList.java
QSmartboardPlugin/src/ru/apertum/qsystem/smartboard/QSBoard.java
QSmartboardPlugin/target/classes/ru/apertum/qsystem/smartboard/PrintRecords.java
QSmartboardPlugin/target/classes/ru/apertum/qsystem/smartboard/QSBoard.java
QSystem/src/ru/apertum/qsystem/common/model/QCustomer.java
QSystem/src/ru/apertum/qsystem/server/controller/Executer.java
QSystem/src/ru/apertum/qsystem/server/model/QService.java
QUser/src/java/ru/apertum/qsys/quser/Form.java
Seeder/sql/V1.8__QSystem_Add_Stored_Procedure.sql

Call John's stored procedure to create real time summary data
Comment out numerous debug statements for easier future debugging

Call store proc

---

QSystem/src/ru/apertum/qsystem/common/Uses.java
QSystem/src/ru/apertum/qsystem/common/model/QCustomer.java
QSystem/src/ru/apertum/qsystem/server/controller/AIndicatorBoard.java
QSystem/src/ru/apertum/qsystem/server/controller/Executer.java
QSystem/src/ru/apertum/qsystem/server/model/ATListModel.java
QSystem/src/ru/apertum/qsystem/server/model/QService.java
QUser/src/java/ru/apertum/qsys/quser/Form.java
QUser/web/include/dialog/addTicketDialog.zul

Second CSR inviting customer no longer affects any box EXCEPT for the Category combo box.
Changes:
- Uses.java - only changes (lots!) are in UTF encoding of Russian text.  Couldn't find code page?
- QCustomer.java - Comment out old debug messages so current debugging is faster
- AIndicatorboard, Executer, ATListmodel - Same
- addTicketDialog.zul - Remove automatic loading, binding from comments and service text boxes
- Form.java - added code to manually get data from now unbound comments, services textboxes

Bug fix search

---

QSystem/src/ru/apertum/qsystem/common/Uses.java
QSystem/src/ru/apertum/qsystem/common/model/QCustomer.java
QSystem/src/ru/apertum/qsystem/server/controller/AIndicatorBoard.java
QSystem/src/ru/apertum/qsystem/server/controller/Executer.java
QSystem/src/ru/apertum/qsystem/server/model/ATListModel.java
QSystem/src/ru/apertum/qsystem/server/model/QService.java
QUser/src/java/ru/apertum/qsys/quser/Form.java
QUser/web/include/dialog/addTicketDialog.zul
functional-tests/src/test/groovy/FlowSpecs.groovy

Remove bdd test

---

QUser/src/java/ru/apertum/qsys/quser/Form.java
QUser/web/include/clientDashboard.zul
QUser/web/include/dialog/addTicketDialog.zul
QUser/web/include/loginForm.zul

In login screen, in add Ticket screen, in Hold Queue
Add isReceptionOffice function to Form.java
- same as getCFMSType function, but more descriptive name

Remove Q Txn display, non-reception offices

---

Seeder/sql/V1.10__QSystem_Update_Stat_Procedures.sql

Fix issues with wait and hold times.

Update Statistics Procedures in MySQL

---

QSystem/src/ru/apertum/qsystem/server/controller/Executer.java
QUser/web/include/clientDashboard.zul
QUser/web/include/dialog/ReportingBug.zul
QUser/web/include/dialog/addTicketDialog.zul
QUser/web/include/dialog/serveCustomerDialog.zul
QUser/web/include/loginForm.zul
QUser/web/index.zul

Get proper return code and error message from John's stored procedure
Disable double clicks on all buttons

Get sql error msg, disable double clicks

---

Seeder/sql/V1.12__QSystem_Update_Stat_Procedures.sql

Add views and update function and procedure

Add views and update function and procedure

---

QSmartboard/src/java/ru/apertum/qsystem/qboard/QBoard.java
QSmartboard/web/js/qsmartboard.js
QSmartboardPlugin/src/ru/apertum/qsystem/smartboard/PrintRecords.java
QSmartboardPlugin/target/classes/ru/apertum/qsystem/smartboard/PrintRecords.java
QSystem/src/ru/apertum/qsystem/server/QServer.java
QUser/src/java/ru/apertum/qsys/quser/Form.java

Have smartboard refresh with new code after rebuild.

Fix board refresh

---

QSystem/src/ru/apertum/qsystem/server/controller/Executer.java
QUser/src/java/ru/apertum/qsys/quser/Form.java
QUser/web/index.zul
Seeder/sql/V1.13__QSystem_CreateTrackingTable.sql

Tracking button clicks in system for debugging.  Database changes now included.

Track clicks

---

QUser/src/java/ru/apertum/qsys/quser/Form.java
QUser/web/WEB-INF/i3-label_en_US.properties
QUser/web/index.zul

Add UI, code, property label for Back Office button

Back office button

---

QUser/src/java/ru/apertum/qsys/quser/Form.java

Fix back office preselection for non reception offices

Fix back office preselection, non reception offices

---

QSmartboard/src/java/ru/apertum/qsystem/qboard/QBoard.java

Code to reload page in Java, if session hashcodes different.
- Should reload page on Openshift redeploy

Code to reload page in Java, if session hashcodes different.

---

QSystem/src/ru/apertum/qsystem/server/controller/Executer.java
QUser/src/java/ru/apertum/qsys/quser/Form.java

New tracking code introduced bug when CSR answered No when asked if they really want to invite citizen from hold queue

Fix return cust to hold

---

QSystem/src/ru/apertum/qsystem/server/QSession.java
QSystem/src/ru/apertum/qsystem/server/QSessions.java

Same as previous Enhancement pull request, but with debugging statements taken out.

Remove Session debugging statements

---

QSystem/src/ru/apertum/qsystem/common/model/QCustomer.java
QSystem/src/ru/apertum/qsystem/server/controller/Executer.java
QSystem/src/ru/apertum/qsystem/server/model/QUser.java
QUser/src/java/ru/apertum/qsys/quser/Form.java
QUser/web/include/clientDashboard.zul
QUser/web/index.zul

Different backgrounds, dev, test, prod
Change title, Citizens on hold
GA Board sorted, only has text for CSRs logged in
Office name now stays after a refresh
Previous services no longer contains duplicates

Enhancements V2

---

QUser/web/include/clientDashboard.zul

Fix column widths on wait queue

Fix column widths on wait queue

---

QSmartboard/src/java/ru/apertum/qsystem/qboard/QBoard.java
QSmartboard/web/index.zul

Delete welcome message, increase size of customer waiting text

Smartboard wait count font size

---

QSystem/src/ru/apertum/qsystem/common/cmd/CmdParams.java
QSystem/src/ru/apertum/qsystem/common/model/QCustomer.java
QSystem/src/ru/apertum/qsystem/server/controller/Executer.java
QUser/src/java/ru/apertum/qsys/quser/Form.java

This sequence is used in the Add ticket screen, the Begin Service button
Also used in the Serve Citizen screen, the Next Service button

Fix bug in Add to queue, invite begin sequence

---

QSystem/src/ru/apertum/qsystem/server/controller/Executer.java
QUser/src/java/ru/apertum/qsys/quser/Form.java

Put back in code to set in_sequence flag for Add Next Service
Added new code to set in_sequence flag for Previous Service (forgot this earlier)

Fix redirect bug

---

QSystem/src/ru/apertum/qsystem/server/controller/Executer.java
QUser/src/java/ru/apertum/qsys/quser/Form.java
QUser/web/include/dialog/serveCustomerDialog.zul

Make background queues more visible when doing back office work

Fix modal background

---

QSystem/src/ru/apertum/qsystem/server/controller/Executer.java
QUser/src/java/ru/apertum/qsys/quser/Form.java

Send Slack message if sequence error for buttons Begin Service, Next Service, Previous Services

Send error messages to Slack if add/invite/begin sequence bugs

---

QSystem/src/ru/apertum/qsystem/server/controller/Executer.java
QUser/src/java/ru/apertum/qsys/quser/Form.java

Fix bug where high priority not getting set if next service same as previous service
- this resulted in wrong client getting selected from the queue when CSR pressed Next Service

Fix sequence bug

---

QUser/src/java/ru/apertum/qsys/quser/Form.java

Fix bug where comments from previous citizen retained for Add Citizen

Clear the comments if a new citizen, via the Add Citizen button

---

QUser/src/java/ru/apertum/qsys/quser/Form.java

To ensure channel correct in Snowplow data

Make a Snowplow call to chooseservice when channel changed.

---

Jenkinsfile
Jenkinsfile_WithBDDTests

Second try at deleting BDD tests

No more bdd tests

---

QUser/web/include/dialog/serveCustomerDialog.zul

Delay implementation of update Quick Transaction status until new system implemented

Hide the Quick Transaction button on the Serve Citizen screen

---

QSystem/src/ru/apertum/qsystem/server/controller/Executer.java

To fix calculations for Snowplow

Remove extra Snowplow beginservice call, on call citizen from hold

---

Seeder/sql/V1.17__QSystem_UpdateWaitPrepTimes.sql

Implement new SQL procedures from John to fix some timing issues

Update procedures to calculate wait and prep times correctly

---

QSystem/src/ru/apertum/qsystem/server/controller/Executer.java

- to prevent null value in Looker Invite Time cell

Add an invitecitizen Snowplow call after next service
